---
include:
  # Firmwares “normais” (same version for both)
  - board: eyelash_sofle_left
    shield: nice_view
    artifact-name: eyelash_sofle_left

  - board: eyelash_sofle_right
    shield: nice_view
    artifact-name: eyelash_sofle_right

  # Optional: build with ZMK Studio (only on left, if you want to use it)
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left

  # Resets for both sides (delete settings/bonds from both sides)
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset_left

  - board: eyelash_sofle_right
    shield: settings_reset
    artifact-name: settings_reset_right
