draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 65.0
  key_h: 60.0
  split_gap: 35.0
  combo_w: 32.0
  combo_h: 28.0
  key_rx: 8.0
  key_ry: 8.0
  inner_pad_w: 3.0
  inner_pad_h: 3.0
  outer_pad_w: 45.0
  outer_pad_h: 60.0
  line_spacing: 1.3
  arc_radius: 8.0
  append_colon_to_layer_header: true
  small_pad: 3.0
  svg_extra_style: |
    /* Modern styling for beautiful keymap visualization */

    /* Define color palette */
    :root {
      --primary-bg: #1a1a1a;
      --secondary-bg: #2d2d2d;
      --key-bg: #3a3a3a;
      --key-border: #555555;
      --text-primary: #ffffff;
      --text-secondary: #b0b0b0;
      --accent-primary: #4f46e5;
      --accent-secondary: #06b6d4;
      --success: #10b981;
      --warning: #f59e0b;
      --error: #ef4444;
    }

    /* Main SVG styling */
    svg.keymap {
      font-family: 'Inter', 'SF Pro Display', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 13px;
      font-weight: 600;
      text-rendering: optimizeLegibility;
      background: linear-gradient(135deg, var(--primary-bg) 0%, var(--secondary-bg) 100%);
      border-radius: 12px;
      box-shadow: 0 20px 40px rgba(0, 0, 0, 0.3);
    }

    /* Key styling with modern appearance */
    rect.key, rect.combo {
      fill: var(--key-bg);
      stroke: var(--key-border);
      stroke-width: 1.5;
      filter: drop-shadow(0 4px 8px rgba(0, 0, 0, 0.2));
      transition: all 0.2s ease;
    }

    rect.key:hover, rect.combo:hover {
      fill: #4a4a4a;
      stroke: var(--accent-primary);
      stroke-width: 2;
    }

    /* Layer headers with gradient */
    text.layer-header {
      font-size: 16px;
      font-weight: 700;
      fill: var(--text-primary);
      text-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
    }

    /* Enhanced color accents for different key types */
    rect.held, rect.combo.held {
      fill: linear-gradient(135deg, var(--accent-primary) 0%, var(--accent-secondary) 100%);
      stroke: var(--accent-primary);
      stroke-width: 2;
    }

    /* Modifier keys */
    rect.modifier {
      fill: linear-gradient(135deg, #374151 0%, #4b5563 100%);
      stroke: #6b7280;
    }

    /* Function keys */
    rect.function {
      fill: linear-gradient(135deg, #7c3aed 0%, #a855f7 100%);
      stroke: #8b5cf6;
    }

    /* Special keys */
    rect.special {
      fill: linear-gradient(135deg, var(--success) 0%, #34d399 100%);
      stroke: var(--success);
    }

    /* Text styling improvements */
    text.key-label {
      fill: var(--text-primary);
      font-weight: 600;
      text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
    }

    text.key-label.shifted {
      fill: var(--text-secondary);
      font-size: 11px;
    }

    /* Combo styling */
    rect.combo {
      fill: linear-gradient(135deg, #f59e0b 0%, #fbbf24 100%);
      stroke: #f59e0b;
      stroke-width: 2;
    }

    /* Enhanced positioning for better readability */
    .sym_sub_text.tap {
      translate: -6px 3px;
      font-size: 22px;
      font-weight: 700;
      fill: var(--text-primary);
    }
    .sym_sub_text.shifted {
      translate: 12px 15px;
      font-size: 11px;
      opacity: 0.9;
      fill: var(--text-secondary);
    }
    .combo.sym_sub_text.tap {
      translate: -2px 2px;
      font-size: 18px;
    }
    .combo.sym_sub_text.shifted {
      translate: 8px 6px;
      font-size: 10px;
      opacity: 0.9;
    }

    /* Toggle keys with better positioning */
    .toggle.shifted {
      translate: -12px 14px;
      font-size: 11px;
      fill: var(--accent-secondary);
    }

    .toggle.hold {
      translate: 15px -25px;
      font-size: 11px;
      fill: var(--accent-primary);
    }

    /* Tap-dance styling */
    .tap_dance.tap {
      translate: -8px 1px;
      font-size: 13px;
      font-weight: 600;
    }
    .tap_dance.shifted {
      translate: 8px 18px;
      font-size: 11px;
      opacity: 0.9;
      fill: var(--text-secondary);
    }

    /* Symbol positioning improvements */
    .sym_by_sym.tap {
      translate: -7px 1px;
      font-size: 14px;
    }
    .sym_by_sym.shifted {
      translate: 11px 13px;
      opacity: 0.9;
      font-size: 11px;
    }

    .combo.sym_by_sym.tap {
      translate: -38px 1px;
      font-size: 16px;
    }
    .combo.sym_by_sym.shifted {
      translate: 38px 22px;
      opacity: 0.9;
      font-size: 10px;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* Hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }

    /* Additional modern effects */
    .key-legend {
      filter: drop-shadow(0 1px 2px rgba(0, 0, 0, 0.3));
    }

    /* Animation for interactive elements */
    @keyframes pulse {
      0% { opacity: 1; }
      50% { opacity: 0.7; }
      100% { opacity: 1; }
    }

    .pulse {
      animation: pulse 2s infinite;
    }

    /* Improved spacing and alignment */
    .key-content {
      display: flex;
      align-items: center;
      justify-content: center;
    }

  shrink_wide_legends: 8
  glyph_tap_size: 20
  glyph_hold_size: 16
  glyph_shifted_size: 14
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Layers
    "&ltq 1 BACKSPACE":
      tap: $$mdi:backspace$$
      hold: "$$mdi:navigation-variant$$"
    "&ltq 3 TAB":
      tap: $$mdi:keyboard-tab$$
      hold: $$mdi:numeric$$
    "&ltq 2 SPACE":
      tap: $$mdi:keyboard-space$$
      hold: $$mdi:symbol$$
    "&ltq 3 ENTER":
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:numeric$$
    "&ltq 1 DELETE":
      tap: $$mdi:backspace-reverse-outline$$
      hold: $$mdi:navigation-variant$$
    # Home rows
    "&hm LEFT_GUI A":
      tap: "A"
      shifted: $$mdi:apple-keyboard-command$$
    "&hm LEFT_ALT S":
      tap: "S"
      shifted: $$mdi:apple-keyboard-option$$
    "&hm LEFT_CONTROL D":
      tap: "D"
      shifted: $$mdi:apple-keyboard-control$$
    "&hm LEFT_SHIFT F":
      tap: "F"
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_SHIFT J":
      tap: "J"
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_CONTROL K":
      tap: "K"
      shifted: $$mdi:apple-keyboard-control$$
    "&hm RIGHT_ALT L":
      tap: "L"
      shifted: $$mdi:apple-keyboard-option$$
    # self behaviors
    "&hm LG(LS(V)) P":
      tap: "P"
      shifted: $$mdi:content-copy$$
    # Mouse
    "&msc SCRL_UP":
      tap: $$mdi:pan-up$$
      hold: ""
      shifted: ""
    "&msc SCRL_DOWN":
      tap: $$mdi:pan-down$$
      hold: ""
      shifted: ""
    "&msc SCRL_LEFT":
      tap: $$mdi:pan-left$$
      hold: ""
      shifted: ""
    "&msc SCRL_RIGHT":
      tap: $$mdi:pan-right$$
      hold: ""
      shifted: ""
    "&mmv MOVE_LEFT":
      tap: $$mdi:menu-left$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mmv MOVE_RIGHT":
      tap: $$mdi:menu-right$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mmv MOVE_UP":
      tap: $$mdi:menu-up$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mmv MOVE_DOWN":
      tap: $$mdi:menu-down$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mkp LCLK":
      tap: $$mdi:mouse-left-click-outline$$
    "&mkp RCLK":
      tap: $$mdi:mouse-right-click-outline$$
    "&mkp MCLK":
      tap: $$mdi:mouse-scroll-wheel$$
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:toggle-switch$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

    # Bluetooth - Enhanced icons
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: "1"
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: "2"
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: "3"
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: "4"
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: "5"
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb-cable$$
      tap: $$mdi:toggle-switch-variant$$
      hold: $$mdi:bluetooth-settings$$
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      tap: $$mdi:chevron-up$$
      hold: $$mdi:arrow-up-bold$$
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      tap: $$mdi:chevron-down$$
      hold: $$mdi:arrow-down-bold$$
    # Reset - Enhanced icons
    "&sys_reset":
      type: bootloader
      tap: $$mdi:restart-alert$$
    "&bootloader":
      tap: $$mdi:download-circle$$

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE:
      tap: "'"
      shifted: '"'
    APOS:
      tap: "'"
      shifted: '"'
    DOUBLE_QUOTES: '"'
    DQT: '"'

    LESS_THAN: <
    LT: <
    PERIOD: "."
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:apple-keyboard-command$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    LEFT_COMMAND: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:apple-keyboard-command$$
    PSCRN: $$mdi:printer-outline$$
    RIGHT_COMMAND: $$mdi:apple-keyboard-command$$
    PAGE_UP:
      tap: "PgUp"
      shifted: ""
    PAGE_DOWN:
      tap: "PgDn"
      shifted: ""
    INSERT:
      tap: "Ins"
      shifted: ""
    # "Meh" key
    LS(LC(LALT)): $$mdi:star-three-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound - Enhanced icons
    C_MUTE: $$mdi:volume-off-variant$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    C_VOLUME_UP: $$mdi:volume-plus$$
    C_VOLUME_DOWN: $$mdi:volume-minus$$

    # Media - Enhanced icons
    C_NEXT: $$mdi:skip-next-circle$$
    C_PREV: $$mdi:skip-previous-circle$$
    C_PP: $$mdi:play-pause-circle$$

    # Bluetooth - Enhanced icons
    BT_CLR: $$mdi:bluetooth-off-variant$$
    BT_SEL: $$mdi:bluetooth-settings$$

    # Settings - Enhanced icons
    C_BRI_UP: $$mdi:brightness-6$$
    C_BRIGHTNESS_INC: $$mdi:brightness-6$$
    C_BRI_DN: $$mdi:brightness-4$$
    C_BRI_DEC: $$mdi:brightness-4$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-4$$

    # System - Enhanced icons
    C_POWER: $$mdi:power-cycle$$
    C_AL_LOCK: $$mdi:lock-alert$$
    K_CANCEL: $$mdi:close-circle$$
    K_FIND: $$mdi:magnify$$
    # Command +
    LG(A):
      tap: "A"
      hold: $$mdi:apple-keyboard-command$$
    LG(S):
      tap: "S"
      hold: $$mdi:apple-keyboard-command$$
    LG(D):
      tap: "D"
      hold: $$mdi:apple-keyboard-command$$
    LG(F):
      tap: "F"
      hold: $$mdi:apple-keyboard-command$$
    LG(Z):
      tap: "Z"
      hold: $$mdi:apple-keyboard-command$$
    LG(X):
      tap: "X"
      hold: $$mdi:apple-keyboard-command$$
    LG(C):
      tap: "C"
      hold: $$mdi:apple-keyboard-command$$
    LG(V):
      tap: "V"
      hold: $$mdi:apple-keyboard-command$$
    # Zoom - Enhanced icons
    RG(RS(A)):
      tap: $$mdi:microphone-variant$$
      hold: zoom
    RG(RS(V)):
      tap: $$mdi:video-variant$$
      hold: zoom

  zmk_combos:
    combo_to_2:
      align: top
    combo_to_3:
      align: top
    combo_bt_clear:
      align: top
      offset: 0.03
    combo_mute:
      align: top
      offset: 0.15
    combo_minus:
      key:
        shifted: "_"
        hold: "-"
    combo_equal:
      key:
        shifted: "+"
        hold: "="
    combo_backslash:
      key:
        shifted: "|"
        hold: \
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"
