draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 0.0
  inner_pad_h: 0.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  svg_extra_style: |
    /* Modern styling for beautiful keymap visualization */

    /* Main SVG styling with light theme */
    svg.keymap {
      font-family: IBM Plex Mono, Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
      background: #ffffffff;
    }

    /* Key styling with light theme */
    rect.key, rect.combo {
      fill: #ffffff;
      stroke: #d1d5db;
      stroke-width: 1.5;
    }

    /* Remove inner padding effect */
    rect.key > rect, rect.combo > rect {
      fill: none;
      stroke: none;
    }

    /* Removed colored borders for cleaner look */

    /* Clean key styling without inner effects */

    /* Layer headers */
    text.layer-header {
      font-size: 18px;
      font-weight: 600;
      fill: #1f2937;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held {
        fill: #ffc;
    }

    /* Text styling improvements with better centering */
    text.key-label {
      fill: #1f2937;
      font-weight: 500;
      text-anchor: middle;
      dominant-baseline: central;
    }

    text.key-label.shifted {
      fill: #6b7280;
      font-size: 12px;
      text-anchor: middle;
      dominant-baseline: central;
    }

    /* Better alignment for stacked text */
    text.key-label.tap {
      text-anchor: middle;
      dominant-baseline: central;
      fill: #1f2937;
      font-weight: 600;
    }

    text.key-label.hold {
      text-anchor: middle;
      dominant-baseline: central;
      fill: #dc2626;
      font-weight: 600;
    }

    /* All text elements should be centered */
    text {
      text-anchor: middle;
      dominant-baseline: central;
    }

    /* Simplified icon colors for cleaner look */

    /* Combo styling for light theme */
    rect.combo {
      fill: #ffffff;
      stroke: #d1d5db;
      stroke-width: 1.5;
    }

    /* Better vertical centering for stacked content */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
      font-weight: 600;
      text-anchor: middle;
      dominant-baseline: central;
      fill: #1f2937;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
      text-anchor: middle;
      dominant-baseline: central;
      fill: #6b7280;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Better positioning for tap/hold behaviors with vertical centering */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
      font-weight: 600;
      fill: #059669;
      text-anchor: middle;
      dominant-baseline: central;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      fill: #dc2626;
      font-weight: 600;
      text-anchor: middle;
      dominant-baseline: central;
      opacity: 1.0;
    }

    /* Improved toggle positioning with vertical centering */
    .toggle.shifted {
      translate: -10px 12px;
      font-size: 12px;
      fill: #6b7280;
      text-anchor: middle;
      dominant-baseline: central;
    }
    .toggle.hold {
      translate: 13px -23px;
      font-size: 12px;
      fill: #dc2626;
      font-weight: 600;
      text-anchor: middle;
      dominant-baseline: central;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }

  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:
    # Layers
    "&ltq 1 BACKSPACE":
      tap: $$mdi:backspace$$
      hold: "$$mdi:navigation-variant$$"
    "&ltq 3 TAB":
      tap: $$mdi:keyboard-tab$$
      hold: $$mdi:numeric$$
    "&ltq 2 SPACE":
      tap: $$mdi:keyboard-space$$
      hold: $$mdi:symbol$$
    "&ltq 3 ENTER":
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:numeric$$
    "&ltq 1 DELETE":
      tap: $$mdi:backspace-reverse-outline$$
      hold: $$mdi:navigation-variant$$
    # Home rows
    "&hm LEFT_GUI A":
      tap: "A"
      shifted: $$mdi:microsoft-windows$$
    "&hm LEFT_ALT S":
      tap: "S"
      shifted: $$mdi:apple-keyboard-option$$
    "&hm LEFT_CONTROL D":
      tap: "D"
      shifted: $$mdi:apple-keyboard-control$$
    "&hm LEFT_SHIFT F":
      tap: "F"
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_SHIFT J":
      tap: "J"
      shifted: $$mdi:apple-keyboard-shift$$
    "&hm RIGHT_CONTROL K":
      tap: "K"
      shifted: $$mdi:apple-keyboard-control$$
    "&hm RIGHT_ALT L":
      tap: "L"
      shifted: $$mdi:apple-keyboard-option$$
    # self behaviors
    "&hm LG(LS(V)) P":
      tap: "P"
      shifted: $$mdi:content-copy$$

    # LGUI key mapping
    "&kp LGUI":
      tap: $$mdi:microsoft-windows$$
    # Mouse
    "&msc SCRL_UP":
      tap: $$mdi:pan-up$$
      hold: ""
      shifted: ""
    "&msc SCRL_DOWN":
      tap: $$mdi:pan-down$$
      hold: ""
      shifted: ""
    "&msc SCRL_LEFT":
      tap: $$mdi:pan-left$$
      hold: ""
      shifted: ""
    "&msc SCRL_RIGHT":
      tap: $$mdi:pan-right$$
      hold: ""
      shifted: ""
    "&mmv MOVE_LEFT":
      tap: $$mdi:menu-left$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mmv MOVE_RIGHT":
      tap: $$mdi:menu-right$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mmv MOVE_UP":
      tap: $$mdi:menu-up$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mmv MOVE_DOWN":
      tap: $$mdi:menu-down$$
      hold: ""
      shifted: $$mdi:mouse$$
    "&mkp LCLK":
      tap: $$mdi:mouse-left-click-outline$$
    "&mkp RCLK":
      tap: $$mdi:mouse-right-click-outline$$
    "&mkp MCLK":
      tap: $$mdi:mouse-scroll-wheel$$
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:toggle-switch$$

    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

    # Bluetooth - Enhanced icons
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-up-bold$$
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-down-bold$$
    # Reset - Enhanced icons
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE:
      tap: "'"
      shifted: '"'
    APOS:
      tap: "'"
      shifted: '"'
    DOUBLE_QUOTES: '"'
    DQT: '"'

    LESS_THAN: <
    LT: <
    PERIOD: "."
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:microsoft-windows$$
    LEFT_GUI: $$mdi:microsoft-windows$$
    LGUI: $$mdi:microsoft-windows$$
    LEFT_COMMAND: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:microsoft-windows$$
    RGUI: $$mdi:microsoft-windows$$
    PSCRN: $$mdi:printer-outline$$
    RIGHT_COMMAND: $$mdi:apple-keyboard-command$$
    PAGE_UP:
      tap: "PgUp"
      shifted: ""
    PAGE_DOWN:
      tap: "PgDn"
      shifted: ""
    INSERT:
      tap: "Ins"
      shifted: ""
    # "Meh" key
    LS(LC(LALT)): $$mdi:star-three-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound - Enhanced icons
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    # Media - Enhanced icons
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth - Enhanced icons
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings - Enhanced icons
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRIGHTNESS_INC: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    C_BRI_DEC: $$mdi:brightness-7$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-7$$

    # System - Enhanced icons
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_FIND: $$mdi:apple-finder$$
    # Command +
    LG(A):
      tap: "A"
      hold: $$mdi:microsoft-windows$$
    LG(S):
      tap: "S"
      hold: $$mdi:microsoft-windows$$
    LG(D):
      tap: "D"
      hold: $$mdi:microsoft-windows$$
    LG(F):
      tap: "F"
      hold: $$mdi:microsoft-windows$$
    LG(Z):
      tap: "Z"
      hold: $$mdi:microsoft-windows$$
    LG(X):
      tap: "X"
      hold: $$mdi:microsoft-windows$$
    LG(C):
      tap: "C"
      hold: $$mdi:microsoft-windows$$
    LG(V):
      tap: "V"
      hold: $$mdi:microsoft-windows$$
    # Zoom - Enhanced icons
    RG(RS(A)):
      tap: $$mdi:microphone$$
      hold: zoom
    RG(RS(V)):
      tap: $$mdi:video$$
      hold: zoom

  zmk_combos:
    combo_to_2:
      align: top
    combo_to_3:
      align: top
    combo_bt_clear:
      align: top
      offset: 0.03
    combo_mute:
      align: top
      offset: 0.15
    combo_minus:
      key:
        shifted: "_"
        hold: "-"
    combo_equal:
      key:
        shifted: "+"
        hold: "="
    combo_backslash:
      key:
        shifted: "|"
        hold: \
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"
